# Generated by Django 4.2.1 on 2023-06-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_conversation_message_remove_conversation_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='value',
            new_name='prompt_value',
        ),
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(default='nothing', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messages',
            name='system_value',
            field=models.TextField(default='nothin'),
            preserve_default=False,
        ),
    ]
