# Generated by Django 4.2.1 on 2023-05-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_additional'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='message_title',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='message',
            field=models.TextField(blank=True, default=None, max_length=2000),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='user',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
